import {
  BrowserWindow,
  app,
  ipcMain,
  desktopCapturer,
  session,
} from "electron";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
import Prism from "prismjs";
import OpenAI from "openai";
import axios from "axios";
import FormData from "form-data";
import fs from "fs";
import path from "path";
import { Buffer } from "buffer";
import { createClient, LiveTranscriptionEvents } from "@deepgram/sdk";
import WebSocket from "ws";

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
import electronSquirrelStartup from "electron-squirrel-startup";

if (electronSquirrelStartup) {
  app.quit();
}

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    height: 1000,
    width: 1300,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      webSecurity: false,
    },
  });

  mainWindow.webContents.session.webRequest.onHeadersReceived(
    (details, callback) => {
      callback({
        responseHeaders: {
          ...details.responseHeaders,
          "Content-Security-Policy": [
            "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:; connect-src 'self' https://api.openai.com;",
          ],
        },
      });
    }
  );

  mainWindow.webContents.session.setPermissionRequestHandler(
    (webContents, permission, callback) => {
      if (permission === "media") {
        callback(true);
      } else {
        callback(false);
      }
    }
  );

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY + "#/main_window");
//  mainWindow.webContents.openDevTools();

  mainWindow.webContents.on("did-finish-load", () => {
    mainWindow.webContents.executeJavaScript(`
      console.log('Applied CSP:', document.querySelector('meta[http-equiv="Content-Security-Policy"]')?.getAttribute('content'));
    `);
  });
};

ipcMain.handle(
  "save-temp-audio-file",
  async (event, audioBuffer: ArrayBuffer) => {
    try {
      const tempFilePath = path.join(
        app.getPath("temp"),
        `temp_audio_${Date.now()}.wav`
      );
      fs.writeFileSync(tempFilePath, Buffer.from(audioBuffer));
      return tempFilePath;
    } catch (error) {
      throw error;
    }
  }
);

ipcMain.handle(
  "transcribe-audio-file",
  async (event, filePath: string, config) => {
    try {
      const formData = new FormData();
      formData.append("file", fs.createReadStream(filePath), "audio.wav");
      formData.append("model", "whisper-1");

      if (config.primaryLanguage && config.primaryLanguage !== "auto") {
        formData.append("language", config.primaryLanguage);
      }
      if (config.secondaryLanguage) {
        formData.append(
          "prompt",
          `This audio may contain ${config.primaryLanguage} and ${config.secondaryLanguage}.`
        );
      }

      const baseUrl = normalizeApiBaseUrl(config.api_base);
      const apiUrl = `${baseUrl}/audio/transcriptions`;
      const response = await axios.post(apiUrl, formData, {
        headers: {
          ...formData.getHeaders(),
          Authorization: `Bearer ${config.openai_key}`,
        },
        maxContentLength: Infinity,
        maxBodyLength: Infinity,
      });

      return response.data;
    } catch (error) {
      throw error;
    } finally {
      fs.unlinkSync(filePath);
    }
  }
);

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the
// dock icon is clicked and there are no other windows open.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

import ElectronStore from "electron-store";

interface StoreSchema {
  config: Record<string, any>;
}

type TypedElectronStore = ElectronStore<StoreSchema> & {
  get: <K extends keyof StoreSchema>(key: K) => StoreSchema[K];
  set: <K extends keyof StoreSchema>(key: K, value: StoreSchema[K]) => void;
  clear: () => void;
};

const store = new ElectronStore<StoreSchema>() as TypedElectronStore;

ipcMain.handle("get-config", () => {
  return store.get("config");
});

ipcMain.handle("set-config", (event, config) => {
  store.set("config", config);
});

ipcMain.handle("parsePDF", async (event, pdfBuffer) => {
  try {
    const pdf = require("pdf-parse");
    const data = await pdf(Buffer.from(pdfBuffer), {
      max: 0,
    });
    return { text: data.text };
  } catch (error) {
    return { error: "Failed to parse PDF: " + error.message };
  }
});

ipcMain.handle("process-image", async (event, imageData) => {
  try {
    const sharp = require("sharp");
    let image;
    if (imageData.startsWith("data:image")) {
      const base64Data = imageData.split(",")[1];
      const imageBuffer = Buffer.from(base64Data, "base64");
      image = sharp(imageBuffer);
    } else {
      throw new Error(
        "Invalid image input: expected Base64 encoded image data"
      );
    }
    const metadata = await image.metadata();
    return `Image size: ${metadata.width}x${metadata.height}, Format: ${metadata.format}`;
  } catch (error) {
    return { error: "Failed to process image: " + error.message };
  }
});

ipcMain.handle("highlightCode", async (event, code, language) => {
  return Prism.highlight(code, Prism.languages[language], language);
});

app.on("before-quit", () => {
  const config = store.get("config") || {};
  const apiInfo = {
    openai_key: config.openai_key || "",
    api_base: config.api_base || "",
    gpt_model: config.gpt_model || "",
    api_call_method: config.api_call_method || "direct",
    primaryLanguage: config.primaryLanguage || "en",
    deepgram_api_key: config.deepgram_api_key || "",
    stt_provider: config.stt_provider || "deepgram",
    sixtydb_api_key: config.sixtydb_api_key || "",
    sixtydb_voice_id: config.sixtydb_voice_id || "",
    tts_autoplay: config.tts_autoplay || false,
  };
  store.clear();
  store.set("config", apiInfo);
});

ipcMain.handle("get-system-audio-stream", async () => {
  try {
    const sources = await desktopCapturer.getSources({
      types: ["window", "screen"],
      fetchWindowIcons: false,
    });
    const audioSources = sources.filter(
      (source) =>
        source.name.toLowerCase().includes("sound") ||
        source.name.toLowerCase().includes("audio")
    );
    return audioSources.map((source) => source.id);
  } catch (error) {
    throw error;
  }
});

app.on("ready", () => {
  session.defaultSession.setDisplayMediaRequestHandler(
    (request, callback) => {
      desktopCapturer.getSources({ types: ["screen"] }).then((sources) => {
        callback({ video: sources[0], audio: "loopback" });
      });
    },
    { useSystemPicker: true }
  );

  ipcMain.handle(
    "transcribe-audio",
    async (event, audioBuffer: ArrayBuffer, config) => {
      try {
        const tempFilePath = path.join(
          app.getPath("temp"),
          `temp_audio_${Date.now()}.wav`
        );
        fs.writeFileSync(tempFilePath, Buffer.from(audioBuffer));

        const formData = new FormData();
        formData.append("file", fs.createReadStream(tempFilePath), {
          filename: "audio.wav",
          contentType: "audio/wav",
        });
        formData.append("model", "whisper-1");

        if (config.primaryLanguage && config.primaryLanguage !== "auto") {
          formData.append("language", config.primaryLanguage);
        }
        if (config.secondaryLanguage) {
          formData.append(
            "prompt",
            `This audio may contain ${config.primaryLanguage} and ${config.secondaryLanguage}.`
          );
        }

        const baseUrl = normalizeApiBaseUrl(config.api_base);
        const apiUrl = `${baseUrl}/audio/transcriptions`;
        const response = await axios.post(apiUrl, formData, {
          headers: {
            ...formData.getHeaders(),
            Authorization: `Bearer ${config.openai_key}`,
          },
          maxContentLength: Infinity,
          maxBodyLength: Infinity,
        });

        fs.unlinkSync(tempFilePath);

        return response.data;
      } catch (error) {
        throw error;
      }
    }
  );
});

ipcMain.handle("test-api-config", async (event, config) => {
  try {
    const axiosInstance = axios.create({
      baseURL: normalizeApiBaseUrl(config.api_base),
      headers: {
        Authorization: `Bearer ${config.openai_key}`,
        "Content-Type": "application/json",
      },
    });

    const response = await axiosInstance.post("/chat/completions", {
      model: config.gpt_model || "gpt-3.5-turbo",
      messages: [{ role: "user", content: "Hello, this is a test." }],
    });

    if (
      response.data.choices &&
      response.data.choices[0] &&
      response.data.choices[0].message
    ) {
      return { success: true };
    } else {
      return { success: false, error: "Unexpected API response structure" };
    }
  } catch (error) {
    if (axios.isAxiosError(error)) {
      if (error.response) {
        return {
          success: false,
          error: `Server responded with error: ${error.response.status} ${error.response.statusText}`,
        };
      } else if (error.request) {
        return {
          success: false,
          error:
            "No response received from server. Please check your network connection and API base URL.",
        };
      } else {
        return {
          success: false,
          error: `Error setting up the request: ${error.message}`,
        };
      }
    }
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error occurred",
    };
  }
});

ipcMain.handle("callOpenAI", async (event, { config, messages, signal }) => {
  try {
    const openai = new OpenAI({
      apiKey: config.openai_key,
      baseURL: normalizeApiBaseUrl(config.api_base),
    });

    const abortController = new AbortController();
    if (signal) {
      signal.addEventListener('abort', () => abortController.abort());
    }

    const response = await openai.chat.completions.create({
      model: config.gpt_model || "gpt-3.5-turbo",
      messages: messages,
    }, { signal: abortController.signal });

    if (
      !response.choices ||
      !response.choices[0] ||
      !response.choices[0].message
    ) {
      throw new Error("Unexpected API response structure");
    }
    return { content: response.choices[0].message.content };
  } catch (error) {
    if (error.name === "AbortError") {
      return { error: "AbortError" };
    }
    return { error: error.message || "Unknown error occurred" };
  }
});

ipcMain.handle("get-desktop-sources", async () => {
  try {
    const sources = await desktopCapturer.getSources({
      types: ["window", "screen"],
    });
    return sources.map((source) => ({
      id: source.id,
      name: source.name,
      thumbnail: source.thumbnail.toDataURL(),
    }));
  } catch (error) {
    return [];
  }
});

function normalizeApiBaseUrl(url: string): string {
  if (!url) return "https://api.openai.com/v1";
  url = url.trim();
  if (!url.startsWith("http://") && !url.startsWith("https://")) {
    url = "https://" + url;
  }
  if (!url.endsWith("/v1")) {
    url = url.endsWith("/") ? url + "v1" : url + "/v1";
  }
  return url;
}

// ---------------------------------------------------------------------------
// Real-time Speech-to-Text (provider-agnostic)
// ---------------------------------------------------------------------------
// The renderer talks to a single set of channels (start-stt / send-audio /
// stop-stt) and listens for unified events (stt-transcript / stt-status /
// stt-error). Internally we route to either Deepgram (via @deepgram/sdk) or
// 60db (via a raw WebSocket). Both expect 16 kHz, mono, 16-bit linear PCM,
// which is exactly what InterviewPage produces.

// Active connections. Only one provider is active at a time.
let deepgramConnection: any = null;
let sixtydbSocket: WebSocket | null = null;
let activeProvider: "deepgram" | "60db" | null = null;

function startDeepgram(event: Electron.IpcMainInvokeEvent, config: any) {
  if (!config.deepgram_key) {
    throw new Error("Deepgram API key missing");
  }
  const deepgram = createClient(config.deepgram_key);
  deepgramConnection = deepgram.listen.live({
    punctuate: true,
    interim_results: false,
    model: "general",
    language: config.primaryLanguage || "en",
    encoding: "linear16",
    sample_rate: 16000,
    endpointing: 1500,
  });

  deepgramConnection.addListener(LiveTranscriptionEvents.Open, () => {
    event.sender.send("stt-status", { status: "open", provider: "deepgram" });
  });

  deepgramConnection.addListener(LiveTranscriptionEvents.Close, () => {
    event.sender.send("stt-status", { status: "closed", provider: "deepgram" });
  });

  deepgramConnection.addListener(
    LiveTranscriptionEvents.Transcript,
    (data: any) => {
      if (
        data &&
        data.is_final &&
        data.channel &&
        data.channel.alternatives &&
        data.channel.alternatives[0]
      ) {
        const transcript = data.channel.alternatives[0].transcript;
        if (transcript) {
          event.sender.send("stt-transcript", { transcript, is_final: true });
        }
      }
    }
  );

  deepgramConnection.addListener(LiveTranscriptionEvents.Error, (err: any) => {
    event.sender.send("stt-error", { provider: "deepgram", error: err });
  });

  return new Promise<void>((resolve, reject) => {
    deepgramConnection.addListener(LiveTranscriptionEvents.Open, () =>
      resolve()
    );
    deepgramConnection.addListener(LiveTranscriptionEvents.Error, reject);
    setTimeout(() => reject(new Error("Deepgram timeout")), 10000);
  });
}

function start60dbStt(event: Electron.IpcMainInvokeEvent, config: any) {
  if (!config.sixtydb_key) {
    throw new Error("60db API key missing");
  }
  const url = `wss://api.60db.ai/ws/stt?apiKey=${encodeURIComponent(
    config.sixtydb_key
  )}`;
  const socket = new WebSocket(url);
  sixtydbSocket = socket;

  return new Promise<void>((resolve, reject) => {
    const timeout = setTimeout(
      () => reject(new Error("60db STT timeout")),
      10000
    );

    socket.on("open", () => {
      // Tell 60db we will stream browser PCM (linear) at 16 kHz.
      const language =
        config.primaryLanguage && config.primaryLanguage !== "auto"
          ? config.primaryLanguage
          : "en";
      socket.send(
        JSON.stringify({
          type: "start",
          languages: [language],
          config: {
            encoding: "linear",
            sample_rate: 16000,
            utterance_end_ms: 1000,
            continuous_mode: true,
            interim_results_frequency: 0,
            audio_enhancement: "adaptive",
            diarize: false,
          },
        })
      );
    });

    socket.on("message", (raw: WebSocket.RawData) => {
      let msg: any;
      try {
        msg = JSON.parse(raw.toString());
      } catch {
        return;
      }

      // Server is ready for audio.
      if (msg.type === "connected") {
        clearTimeout(timeout);
        event.sender.send("stt-status", { status: "open", provider: "60db" });
        resolve();
        return;
      }

      // Final transcript. We only forward the canonical (speech_final) result
      // with non-empty text, mirroring the Deepgram is_final filter.
      if (
        msg.type === "transcription" &&
        msg.speech_final === true &&
        msg.text &&
        msg.text.trim()
      ) {
        event.sender.send("stt-transcript", {
          transcript: msg.text,
          is_final: true,
        });
        return;
      }

      if (msg.type === "error") {
        event.sender.send("stt-error", { provider: "60db", error: msg });
      }
    });

    socket.on("error", (err) => {
      clearTimeout(timeout);
      event.sender.send("stt-error", { provider: "60db", error: err.message });
      reject(err);
    });

    socket.on("close", () => {
      event.sender.send("stt-status", { status: "closed", provider: "60db" });
    });
  });
}

ipcMain.handle("start-stt", async (event, config) => {
  try {
    const provider: "deepgram" | "60db" =
      config.stt_provider === "60db" ? "60db" : "deepgram";
    activeProvider = provider;

    if (provider === "60db") {
      await start60dbStt(event, config);
    } else {
      await startDeepgram(event, config);
    }
    return { success: true };
  } catch (error) {
    activeProvider = null;
    return { success: false, error: error.message };
  }
});

ipcMain.handle("send-audio", async (event, audioData) => {
  try {
    const buffer = Buffer.from(audioData);
    if (activeProvider === "deepgram" && deepgramConnection) {
      deepgramConnection.send(buffer);
    } else if (
      activeProvider === "60db" &&
      sixtydbSocket &&
      sixtydbSocket.readyState === WebSocket.OPEN
    ) {
      sixtydbSocket.send(
        JSON.stringify({
          type: "audio",
          audio: buffer.toString("base64"),
          encoding: "linear",
          sample_rate: 16000,
        })
      );
    }
  } catch (error) {
    console.error("failed to send audio to STT provider:", error);
  }
});

ipcMain.handle("stop-stt", () => {
  if (deepgramConnection) {
    try {
      deepgramConnection.finish();
    } catch {
      /* ignore */
    }
    deepgramConnection = null;
  }
  if (sixtydbSocket) {
    try {
      if (sixtydbSocket.readyState === WebSocket.OPEN) {
        sixtydbSocket.send(JSON.stringify({ type: "stop" }));
      }
      sixtydbSocket.close();
    } catch {
      /* ignore */
    }
    sixtydbSocket = null;
  }
  activeProvider = null;
});

// ---------------------------------------------------------------------------
// 60db Text-to-Speech + voices
// ---------------------------------------------------------------------------

ipcMain.handle("speak-60db", async (event, { text, config }) => {
  try {
    if (!config.sixtydb_api_key) {
      throw new Error("60db API key missing");
    }
    if (!text || !text.trim()) {
      throw new Error("No text to synthesize");
    }
    // Non-streaming synthesis: returns base64 audio in JSON. We default to mp3
    // so the renderer can play it directly via a data: URI.
    const response = await axios.post(
      "https://api.60db.ai/tts-synthesize",
      {
        text: text.slice(0, 5000),
        voice_id: config.sixtydb_voice_id || undefined,
        output_format: "mp3",
        speed: 1,
      },
      {
        headers: {
          Authorization: `Bearer ${config.sixtydb_api_key}`,
          "Content-Type": "application/json",
        },
        maxContentLength: Infinity,
        maxBodyLength: Infinity,
      }
    );

    const data = response.data || {};
    if (!data.audio_base64) {
      throw new Error(data.message || "60db returned no audio");
    }
    return {
      success: true,
      audio_base64: data.audio_base64,
      output_format: data.output_format || "mp3",
    };
  } catch (error: any) {
    const message = axios.isAxiosError(error)
      ? error.response
        ? `60db TTS error: ${error.response.status} ${error.response.statusText}`
        : error.message
      : error.message || "Unknown error";
    return { success: false, error: message };
  }
});

ipcMain.handle("get-60db-voices", async (event, config) => {
  try {
    if (!config.sixtydb_api_key) {
      throw new Error("60db API key missing");
    }
    const response = await axios.get("https://api.60db.ai/myvoices", {
      headers: { Authorization: `Bearer ${config.sixtydb_api_key}` },
    });
    const data = response.data || {};
    return { success: true, voices: Array.isArray(data.data) ? data.data : [] };
  } catch (error: any) {
    const message = axios.isAxiosError(error)
      ? error.response
        ? `60db voices error: ${error.response.status} ${error.response.statusText}`
        : error.message
      : error.message || "Unknown error";
    return { success: false, error: message, voices: [] };
  }
});
