import {
  BrowserWindow,
  app,
  ipcMain,
  desktopCapturer,
  session,
  globalShortcut,
  screen,
  dialog,
  Tray,
  Menu,
  nativeImage,
  clipboard,
  shell,
  safeStorage,
} from "electron";
import trayIconPath from "./assets/icon.ico";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
import Prism from "prismjs";
import axios from "axios";
import FormData from "form-data";
import fs from "fs";
import path from "path";
import { Buffer } from "buffer";
import { createClient, LiveTranscriptionEvents } from "@deepgram/sdk";
import WebSocket from "ws";
import { askWithMode, getProvider } from "./llm/router";
import { normalizeApiBaseUrl } from "./llm/util";
import { nextMode, type InterviewMode } from "./llm/modes";
import { callHHTool, killHHBridge, setHHEventListener } from "./pythonBridge";
import { initJobAutomation, rescheduleJobAutomation, clampIntervalHours } from "./jobAutomation";
import * as superjob from "./superjob";
import { fetchFlRuFeed } from "./flRuFeed";
import * as tts from "./tts";

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
import electronSquirrelStartup from "electron-squirrel-startup";

if (electronSquirrelStartup) {
  app.quit();
}

type HudPosition = "top-left" | "top-right" | "bottom-left" | "bottom-right" | "top-center" | "bottom-center";

// The overlay window is now the whole app (chat, settings, knowledge base) -
// there used to be a separate 1300x1000 control-panel window, removed in
// favor of a single content-protected window. hudWindow stays separate: a
// deliberately tiny, non-interactive status readout.
let overlayWindow: BrowserWindow | null = null;
let hudWindow: BrowserWindow | null = null;
let tray: Tray | null = null;
let overlayClickThrough = false;
let currentMode: InterviewMode = "coding";
let isQuitting = false;

const HUD_WIDTH = 260;
const HUD_HEIGHT = 36;
const HUD_MARGIN = 16;

// Sends an IPC event to every live window (app window, HUD) so both stay in
// sync even though they're separate renderer processes.
function broadcast(channel: string, payload?: any): void {
  for (const win of [overlayWindow, hudWindow]) {
    if (win && !win.isDestroyed()) {
      win.webContents.send(channel, payload);
    }
  }
}

function computeHudBounds(position: HudPosition): { x: number; y: number } {
  const { x: areaX, y: areaY, width, height } = screen.getPrimaryDisplay().workArea;
  switch (position) {
    case "top-left":
      return { x: areaX + HUD_MARGIN, y: areaY + HUD_MARGIN };
    case "top-right":
      return { x: areaX + width - HUD_WIDTH - HUD_MARGIN, y: areaY + HUD_MARGIN };
    case "bottom-left":
      return { x: areaX + HUD_MARGIN, y: areaY + height - HUD_HEIGHT - HUD_MARGIN };
    case "bottom-right":
      return { x: areaX + width - HUD_WIDTH - HUD_MARGIN, y: areaY + height - HUD_HEIGHT - HUD_MARGIN };
    case "bottom-center":
      return { x: areaX + Math.round((width - HUD_WIDTH) / 2), y: areaY + height - HUD_HEIGHT - HUD_MARGIN };
    case "top-center":
    default:
      return { x: areaX + Math.round((width - HUD_WIDTH) / 2), y: areaY + HUD_MARGIN };
  }
}

// The whole app: chat, settings, knowledge base. Content-protected (invisible
// to screen capture) regardless of size, so there's no stealth reason to keep
// it small - it lives in the tray instead of the taskbar/Alt-Tab list, and
// closing it (Alt-F4 - there's no frame/close button) hides it rather than
// quitting; only the tray's own Quit item exits.
const createOverlayWindow = (): void => {
  if (overlayWindow && !overlayWindow.isDestroyed()) {
    return;
  }

  const savedConfig = store.get("config") || {};
  const savedBounds = savedConfig.overlay_bounds;
  overlayClickThrough = !!savedConfig.overlay_click_through_always_on;

  overlayWindow = new BrowserWindow({
    width: savedBounds?.width || 520,
    height: savedBounds?.height || 780,
    minWidth: 400,
    minHeight: 520,
    x: savedBounds?.x,
    y: savedBounds?.y,
    frame: false,
    transparent: true,
    resizable: true,
    skipTaskbar: true,
    hasShadow: true,
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      webSecurity: false,
    },
  });

  overlayWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        "Content-Security-Policy": [
          "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:; connect-src 'self' https://api.openai.com;",
        ],
      },
    });
  });

  overlayWindow.webContents.session.setPermissionRequestHandler((webContents, permission, callback) => {
    callback(permission === "media");
  });

  overlayWindow.setAlwaysOnTop(true, "screen-saver");
  overlayWindow.setContentProtection(true);
  overlayWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  overlayWindow.setIgnoreMouseEvents(overlayClickThrough, { forward: true });
  overlayWindow.setOpacity(typeof savedConfig.window_opacity === "number" ? savedConfig.window_opacity : 1);

  overlayWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY + "#/overlay");
  overlayWindow.once("ready-to-show", () => {
    // Only the very first open should grab focus - the hotkey/tray toggle
    // re-shows via showInactive() so it doesn't steal focus from whatever
    // the user was doing.
    overlayWindow?.show();
  });

  overlayWindow.on("close", (event) => {
    if (!isQuitting) {
      event.preventDefault();
      overlayWindow?.hide();
      broadcast("overlay-visibility-changed", { visible: false });
    }
  });

  const persistBounds = () => {
    if (!overlayWindow) return;
    const config = store.get("config") || {};
    store.set("config", { ...config, overlay_bounds: overlayWindow.getBounds() });
  };
  overlayWindow.on("moved", persistBounds);
  overlayWindow.on("resized", persistBounds);

  overlayWindow.on("closed", () => {
    overlayWindow = null;
  });
};

// Shared by the hotkey, the IPC handler, and the tray menu - avoids three
// copies of the same show/hide/create logic drifting apart.
function toggleOverlayWindow(): boolean {
  if (!overlayWindow || overlayWindow.isDestroyed()) {
    createOverlayWindow();
    broadcast("overlay-visibility-changed", { visible: true });
    return true;
  }
  if (overlayWindow.isVisible()) {
    overlayWindow.hide();
    broadcast("overlay-visibility-changed", { visible: false });
    return false;
  }
  overlayWindow.showInactive();
  broadcast("overlay-visibility-changed", { visible: true });
  return true;
}

// Read-only status readout - shows whether the overlay is visible and
// whether click-through ("cursor protection") is on, so that information
// isn't lost when the overlay itself is hidden. Never receives input and is
// itself excluded from screen capture, same as the overlay.
const createHudWindow = (): void => {
  if (hudWindow && !hudWindow.isDestroyed()) {
    return;
  }

  const savedConfig = store.get("config") || {};
  const position: HudPosition = savedConfig.hud_position || "top-right";
  const { x, y } = computeHudBounds(position);

  hudWindow = new BrowserWindow({
    width: HUD_WIDTH,
    height: HUD_HEIGHT,
    x,
    y,
    frame: false,
    transparent: true,
    resizable: false,
    skipTaskbar: true,
    hasShadow: false,
    focusable: false,
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      webSecurity: false,
    },
  });

  hudWindow.setAlwaysOnTop(true, "screen-saver");
  hudWindow.setContentProtection(true);
  hudWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  hudWindow.setIgnoreMouseEvents(true);

  hudWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY + "#/hud");
  hudWindow.once("ready-to-show", () => {
    hudWindow?.showInactive();
  });

  hudWindow.on("closed", () => {
    hudWindow = null;
  });
};

function repositionHud(position: HudPosition): void {
  if (!hudWindow || hudWindow.isDestroyed()) return;
  const { x, y } = computeHudBounds(position);
  hudWindow.setPosition(x, y);
}

function createTray(): void {
  if (tray) return;

  const icon = nativeImage.createFromPath(trayIconPath);
  tray = new Tray(icon.isEmpty() ? icon : icon.resize({ width: 16, height: 16 }));
  tray.setToolTip("Interview Assistant");
  tray.on("click", () => toggleOverlayWindow());
  updateTrayMenu();
}

function updateTrayMenu(): void {
  if (!tray) return;
  const visible = !!overlayWindow && !overlayWindow.isDestroyed() && overlayWindow.isVisible();
  const menu = Menu.buildFromTemplate([
    { label: visible ? "Hide Window" : "Show Window", click: () => toggleOverlayWindow() },
    { type: "separator" },
    {
      // Fail-safe: if click-through gets stuck on, the window itself is
      // unclickable, so this needs to be reachable from outside it.
      label: "Click-through (mouse passes through window)",
      type: "checkbox",
      checked: overlayClickThrough,
      click: () => {
        overlayClickThrough = !overlayClickThrough;
        overlayWindow?.setIgnoreMouseEvents(overlayClickThrough, { forward: true });
        broadcast("hotkey", { action: "click-through-changed", value: overlayClickThrough });
        updateTrayMenu();
      },
    },
    { type: "separator" },
    {
      label: "Quit",
      click: () => {
        isQuitting = true;
        app.quit();
      },
    },
  ]);
  tray.setContextMenu(menu);
}

interface HotkeyDef {
  id: string;
  label: string;
  accelerator: string;
  handler: () => void;
}

// Registration status per hotkey, so failures (usually a conflict with
// another app already holding that combo) are visible instead of silent -
// globalShortcut.register() returns false on conflict, it does not throw.
const hotkeyStatus = new Map<string, { accelerator: string; registered: boolean }>();

// Triple-modifier combos to cut down on collisions with other apps' global
// hotkeys (Ctrl+Shift+H/Enter/X in particular are commonly already taken).
// Overridable per-id via config.hotkey_overrides, see getHotkeyDefs().
const DEFAULT_ACCELERATORS: Record<string, string> = {
  "toggle-overlay": "CommandOrControl+Alt+Shift+O",
  "ask-now": "CommandOrControl+Alt+Shift+Enter",
  "cycle-mode": "CommandOrControl+Shift+M",
  "clear-transcript": "CommandOrControl+Alt+Shift+X",
  "click-through": "CommandOrControl+Shift+L",
  "region-select": "CommandOrControl+Alt+Shift+S",
  "toggle-auto-answer": "CommandOrControl+Alt+Shift+A",
  "regenerate-last": "CommandOrControl+Alt+Shift+R",
  "model-slot-1": "CommandOrControl+Alt+1",
  "model-slot-2": "CommandOrControl+Alt+2",
  "model-slot-3": "CommandOrControl+Alt+3",
  "model-slot-4": "CommandOrControl+Alt+4",
  "model-slot-5": "CommandOrControl+Alt+5",
};

const MODEL_SLOT_COUNT = 5;

function getHotkeyDefs(config: any = {}): HotkeyDef[] {
  const overrides: Record<string, string> = config.hotkey_overrides || {};
  const accel = (id: string) => overrides[id] || DEFAULT_ACCELERATORS[id];

  return [
    {
      id: "toggle-overlay",
      label: "Show/hide overlay",
      accelerator: accel("toggle-overlay"),
      handler: () => toggleOverlayWindow(),
    },
    {
      id: "ask-now",
      label: "Ask now",
      accelerator: accel("ask-now"),
      handler: () => broadcast("hotkey", { action: "ask-now" }),
    },
    {
      id: "cycle-mode",
      label: "Cycle mode",
      accelerator: accel("cycle-mode"),
      handler: () => {
        currentMode = nextMode(currentMode);
        broadcast("mode-changed", { mode: currentMode });
      },
    },
    {
      id: "clear-transcript",
      label: "Clear transcript",
      accelerator: accel("clear-transcript"),
      handler: () => broadcast("hotkey", { action: "clear-transcript" }),
    },
    {
      id: "click-through",
      label: "Toggle click-through",
      accelerator: accel("click-through"),
      handler: () => {
        if (!overlayWindow || overlayWindow.isDestroyed()) return;
        overlayClickThrough = !overlayClickThrough;
        overlayWindow.setIgnoreMouseEvents(overlayClickThrough, { forward: true });
        broadcast("hotkey", { action: "click-through-changed", value: overlayClickThrough });
        updateTrayMenu();
      },
    },
    {
      id: "region-select",
      label: "Screenshot (region select)",
      accelerator: accel("region-select"),
      handler: () => broadcast("hotkey", { action: "region-select" }),
    },
    {
      id: "toggle-auto-answer",
      label: "Toggle auto-answer",
      accelerator: accel("toggle-auto-answer"),
      handler: () => broadcast("hotkey", { action: "toggle-auto-answer" }),
    },
    {
      id: "regenerate-last",
      label: "Regenerate last answer",
      accelerator: accel("regenerate-last"),
      handler: () => broadcast("hotkey", { action: "regenerate-last" }),
    },
    ...Array.from({ length: MODEL_SLOT_COUNT }, (_, i) => {
      const slot = i + 1;
      const id = `model-slot-${slot}`;
      return {
        id,
        label: `Switch to model slot ${slot}`,
        accelerator: accel(id),
        handler: () => broadcast("hotkey", { action: "switch-model-slot", slot }),
      };
    }),
  ];
}

function registerGlobalShortcuts(): void {
  globalShortcut.unregisterAll();
  hotkeyStatus.clear();

  const config = store.get("config") || {};
  for (const def of getHotkeyDefs(config)) {
    const registered = globalShortcut.register(def.accelerator, def.handler);
    hotkeyStatus.set(def.id, { accelerator: def.accelerator, registered });
    if (!registered) {
      console.warn(
        `[hotkeys] Failed to register "${def.accelerator}" (${def.label}) - it's probably already bound by another app.`
      );
    }
  }
}

ipcMain.handle("toggle-overlay", () => ({ visible: toggleOverlayWindow() }));

ipcMain.handle("get-mode", () => currentMode);

ipcMain.handle("set-mode", (event, mode: InterviewMode) => {
  currentMode = mode;
  broadcast("mode-changed", { mode: currentMode });
});

ipcMain.handle("get-overlay-status", () => ({
  visible: !!overlayWindow && !overlayWindow.isDestroyed() && overlayWindow.isVisible(),
  clickThrough: overlayClickThrough,
}));

ipcMain.handle("get-hotkey-status", () => {
  const config = store.get("config") || {};
  return getHotkeyDefs(config).map((def) => ({
    id: def.id,
    label: def.label,
    accelerator: def.accelerator,
    registered: hotkeyStatus.get(def.id)?.registered ?? false,
  }));
});

ipcMain.handle("set-hotkey", (event, { id, accelerator }: { id: string; accelerator: string }) => {
  const config = store.get("config") || {};
  const overrides = { ...(config.hotkey_overrides || {}) };
  if (accelerator) {
    overrides[id] = accelerator;
  } else {
    delete overrides[id];
  }
  store.set("config", { ...config, hotkey_overrides: overrides });
  registerGlobalShortcuts();

  return getHotkeyDefs(store.get("config") || {}).map((def) => ({
    id: def.id,
    label: def.label,
    accelerator: def.accelerator,
    registered: hotkeyStatus.get(def.id)?.registered ?? false,
  }));
});

ipcMain.handle("set-hud-position", (event, position: HudPosition) => {
  const config = store.get("config") || {};
  store.set("config", { ...config, hud_position: position });
  repositionHud(position);
});

// Generic single-file picker - used by the Jobs tab for the apply_vacancies
// cover-letter file and the create_resume template path. Doesn't persist
// anything to config (unlike the folder pickers above), it's a one-shot pick.
ipcMain.handle("choose-file", async (_event, filters?: Array<{ name: string; extensions: string[] }>) => {
  const result = await dialog.showOpenDialog({ properties: ["openFile"], filters });
  if (result.canceled || !result.filePaths[0]) {
    return { canceled: true };
  }
  return { canceled: false, path: result.filePaths[0] };
});

ipcMain.handle("choose-recordings-folder", async () => {
  const result = await dialog.showOpenDialog({ properties: ["openDirectory", "createDirectory"] });
  if (result.canceled || !result.filePaths[0]) {
    return { canceled: true };
  }
  const config = store.get("config") || {};
  store.set("config", { ...config, recordings_folder: result.filePaths[0] });
  return { canceled: false, path: result.filePaths[0] };
});

ipcMain.handle(
  "save-recording",
  async (event, { buffer, meetingName }: { buffer: ArrayBuffer; meetingName?: string }) => {
    const config = store.get("config") || {};
    const baseFolder = config.recordings_folder || path.join(app.getPath("documents"), "Interview-Assistant Recordings");

    const safeName = (meetingName || "").trim().replace(/[<>:"/\\|?*]+/g, "_").slice(0, 80);
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const meetingFolder = path.join(baseFolder, safeName || timestamp);

    fs.mkdirSync(meetingFolder, { recursive: true });
    const filePath = path.join(meetingFolder, `audio-${timestamp}.webm`);
    fs.writeFileSync(filePath, Buffer.from(buffer));

    return { path: filePath };
  }
);

ipcMain.handle(
  "save-transcript",
  async (event, { markdown, meetingName }: { markdown: string; meetingName?: string }) => {
    const config = store.get("config") || {};
    const baseFolder = config.recordings_folder || path.join(app.getPath("documents"), "Interview-Assistant Recordings");

    const safeName = (meetingName || "").trim().replace(/[<>:"/\\|?*]+/g, "_").slice(0, 80);
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const meetingFolder = path.join(baseFolder, safeName || timestamp);

    fs.mkdirSync(meetingFolder, { recursive: true });
    const filePath = path.join(meetingFolder, `transcript-${timestamp}.md`);
    fs.writeFileSync(filePath, markdown, "utf-8");

    return { path: filePath };
  }
);

// Used by RecordingsPage for non-audio files (transcripts) - a plain <a
// href="file://..."> would navigate the whole window away from the app
// instead of opening in the OS default handler, so this goes through
// shell.openPath instead.
ipcMain.handle("open-path", (event, filePath: string) => {
  shell.openPath(filePath);
});

// Used by Jobs tab platforms that have no automation (Habr Career,
// LinkedIn) - opens a prefilled search URL in the OS default browser
// instead of scraping/automating those sites.
ipcMain.handle("open-external", (event, url: string) => {
  if (/^https?:\/\//i.test(url)) shell.openExternal(url);
});

ipcMain.handle("set-window-opacity", (event, value: number) => {
  const clamped = Math.min(1, Math.max(0.15, value));
  overlayWindow?.setOpacity(clamped);
  const config = store.get("config") || {};
  store.set("config", { ...config, window_opacity: clamped });
});

ipcMain.handle("choose-obsidian-folder", async () => {
  const result = await dialog.showOpenDialog({ properties: ["openDirectory"] });
  if (result.canceled || !result.filePaths[0]) {
    return { canceled: true };
  }
  const config = store.get("config") || {};
  store.set("config", { ...config, obsidian_vault_path: result.filePaths[0] });
  return { canceled: false, path: result.filePaths[0] };
});

function walkMarkdownFiles(root: string, dir: string, out: string[]): void {
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    if (entry.name.startsWith(".")) continue;
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walkMarkdownFiles(root, fullPath, out);
    } else if (entry.isFile() && entry.name.toLowerCase().endsWith(".md")) {
      out.push(path.relative(root, fullPath).split(path.sep).join("/"));
    }
  }
}

ipcMain.handle("list-obsidian-notes", (event, vaultPath: string) => {
  if (!vaultPath) return [];
  const out: string[] = [];
  walkMarkdownFiles(vaultPath, vaultPath, out);
  return out.sort();
});

ipcMain.handle("read-obsidian-note", (event, { vaultPath, relativePath }: { vaultPath: string; relativePath: string }) => {
  const root = path.resolve(vaultPath);
  const target = path.resolve(root, relativePath);
  if (!target.startsWith(root)) {
    throw new Error("Invalid note path");
  }
  return fs.readFileSync(target, "utf-8");
});

ipcMain.handle("list-recordings", () => {
  const config = store.get("config") || {};
  const baseFolder = config.recordings_folder || path.join(app.getPath("documents"), "Interview-Assistant Recordings");
  if (!fs.existsSync(baseFolder)) return [];

  const meetings: { name: string; files: { name: string; path: string; size: number; mtime: number }[] }[] = [];
  for (const entry of fs.readdirSync(baseFolder, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const meetingFolder = path.join(baseFolder, entry.name);
    const files = fs
      .readdirSync(meetingFolder, { withFileTypes: true })
      .filter((f) => f.isFile())
      .map((f) => {
        const filePath = path.join(meetingFolder, f.name);
        const stat = fs.statSync(filePath);
        return { name: f.name, path: filePath, size: stat.size, mtime: stat.mtimeMs };
      });
    meetings.push({ name: entry.name, files });
  }
  return meetings.sort((a, b) => (b.files[0]?.mtime || 0) - (a.files[0]?.mtime || 0));
});

ipcMain.handle("search-transcripts", (_event, query: string) => {
  const trimmed = (query || "").trim();
  if (!trimmed) return [];

  const config = store.get("config") || {};
  const baseFolder = config.recordings_folder || path.join(app.getPath("documents"), "Interview-Assistant Recordings");
  if (!fs.existsSync(baseFolder)) return [];

  const needle = trimmed.toLowerCase();
  const results: { meetingName: string; filePath: string; snippet: string; mtime: number }[] = [];

  for (const entry of fs.readdirSync(baseFolder, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const meetingFolder = path.join(baseFolder, entry.name);
    for (const f of fs.readdirSync(meetingFolder, { withFileTypes: true })) {
      if (!f.isFile() || !f.name.startsWith("transcript-") || !f.name.endsWith(".md")) continue;
      const filePath = path.join(meetingFolder, f.name);
      const content = fs.readFileSync(filePath, "utf-8");
      const lower = content.toLowerCase();
      const matchIndex = lower.indexOf(needle);
      if (matchIndex === -1) continue;
      const snippetStart = Math.max(0, matchIndex - 80);
      const snippetEnd = Math.min(content.length, matchIndex + needle.length + 80);
      const snippet = (snippetStart > 0 ? "..." : "") + content.slice(snippetStart, snippetEnd).replace(/\s+/g, " ") + (snippetEnd < content.length ? "..." : "");
      results.push({ meetingName: entry.name, filePath, snippet, mtime: fs.statSync(filePath).mtimeMs });
    }
  }
  return results.sort((a, b) => b.mtime - a.mtime).slice(0, 50);
});

ipcMain.handle(
  "save-temp-audio-file",
  async (event, audioBuffer: ArrayBuffer) => {
    try {
      const tempFilePath = path.join(
        app.getPath("temp"),
        `temp_audio_${Date.now()}.wav`
      );
      fs.writeFileSync(tempFilePath, Buffer.from(audioBuffer));
      return tempFilePath;
    } catch (error) {
      throw error;
    }
  }
);

ipcMain.handle(
  "transcribe-audio-file",
  async (event, filePath: string, config) => {
    try {
      const formData = new FormData();
      formData.append("file", fs.createReadStream(filePath), "audio.wav");
      formData.append("model", "whisper-1");

      if (config.primaryLanguage && config.primaryLanguage !== "auto") {
        formData.append("language", config.primaryLanguage);
      }
      if (config.secondaryLanguage) {
        formData.append(
          "prompt",
          `This audio may contain ${config.primaryLanguage} and ${config.secondaryLanguage}.`
        );
      }

      const baseUrl = normalizeApiBaseUrl(config.api_base);
      const apiUrl = `${baseUrl}/audio/transcriptions`;
      const response = await axios.post(apiUrl, formData, {
        headers: {
          ...formData.getHeaders(),
          Authorization: `Bearer ${config.openai_key}`,
        },
        maxContentLength: Infinity,
        maxBodyLength: Infinity,
      });

      return response.data;
    } catch (error) {
      throw error;
    } finally {
      fs.unlinkSync(filePath);
    }
  }
);

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  registerGlobalShortcuts();
  createOverlayWindow();
  createHudWindow();
  createTray();
  overlayWindow?.on("show", updateTrayMenu);
  overlayWindow?.on("hide", updateTrayMenu);
});

app.on("before-quit", () => {
  isQuitting = true;
});

app.on("will-quit", () => {
  globalShortcut.unregisterAll();
  killHHBridge();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the
// dock icon is clicked and there are no other windows open.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createOverlayWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

import ElectronStore from "electron-store";

interface StoreSchema {
  config: Record<string, any>;
}

type TypedElectronStore = ElectronStore<StoreSchema> & {
  get: <K extends keyof StoreSchema>(key: K) => StoreSchema[K];
  set: <K extends keyof StoreSchema>(key: K, value: StoreSchema[K]) => void;
  clear: () => void;
};

const store = new ElectronStore<StoreSchema>() as TypedElectronStore;

setHHEventListener((data) => broadcast("hh-event", data));

ipcMain.handle("hh-call", async (_event, { method, params }: { method: string; params?: Record<string, any> }) => {
  const config = store.get("config") || {};
  return callHHTool(config.python_path || "python", method, params || {});
});

ipcMain.handle("get-job-automation-status", () => {
  return (store.get("config") || {}).job_automation || {};
});

// SuperJob credentials/tokens are read through decryptConfig() (declared
// below) since they're stored under the same ENCRYPTED_CONFIG_KEYS scheme as
// the rest of the app's secrets.
async function ensureSuperJobToken(): Promise<{ accessToken: string; apiAppId: string }> {
  const config = decryptConfig(store.get("config") || {});
  const apiAppId = config.superjob_api_app_id || "";
  if (!apiAppId) throw new Error("SuperJob is not configured - set your API App ID in Settings.");

  const expiresAt = config.superjob_token_expires_at || 0;
  if (config.superjob_access_token && expiresAt > Date.now() + 60_000) {
    return { accessToken: config.superjob_access_token, apiAppId };
  }
  if (!config.superjob_refresh_token) {
    throw new Error("Not signed in to SuperJob - sign in from the Jobs tab first.");
  }

  const tokens = await superjob.refreshTokens(config.superjob_refresh_token, {
    clientId: config.superjob_client_id || "",
    clientSecret: config.superjob_client_secret || "",
    apiAppId,
  });
  const rawConfig = store.get("config") || {};
  store.set(
    "config",
    encryptConfig({
      ...decryptConfig(rawConfig),
      superjob_access_token: tokens.access_token,
      superjob_refresh_token: tokens.refresh_token,
      superjob_token_expires_at: tokens.expires_at,
    })
  );
  return { accessToken: tokens.access_token, apiAppId };
}

ipcMain.handle("superjob-login", async () => {
  const config = decryptConfig(store.get("config") || {});
  try {
    const tokens = await superjob.login({
      login: config.superjob_login || "",
      password: config.superjob_password || "",
      clientId: config.superjob_client_id || "",
      clientSecret: config.superjob_client_secret || "",
      apiAppId: config.superjob_api_app_id || "",
    });
    store.set(
      "config",
      encryptConfig({
        ...config,
        superjob_access_token: tokens.access_token,
        superjob_refresh_token: tokens.refresh_token,
        superjob_token_expires_at: tokens.expires_at,
      })
    );
    return { status: "ok" };
  } catch (err: any) {
    return { status: "error", message: err?.response?.data?.error_description || err.message };
  }
});

ipcMain.handle("superjob-status", () => {
  const config = decryptConfig(store.get("config") || {});
  return { authorized: !!config.superjob_refresh_token };
});

ipcMain.handle("superjob-logout", () => {
  const config = store.get("config") || {};
  store.set("config", {
    ...config,
    superjob_access_token: undefined,
    superjob_refresh_token: undefined,
    superjob_token_expires_at: undefined,
  });
});

ipcMain.handle("superjob-search", async (_event, params: superjob.SuperJobSearchParams) => {
  try {
    const { accessToken, apiAppId } = await ensureSuperJobToken();
    return { status: "ok", ...(await superjob.searchVacancies(accessToken, apiAppId, params)) };
  } catch (err: any) {
    return { status: "error", message: err?.response?.data?.error_description || err.message };
  }
});

ipcMain.handle("fl-ru-feed", async () => {
  try {
    return { status: "ok", items: await fetchFlRuFeed() };
  } catch (err: any) {
    return { status: "error", message: err.message };
  }
});

ipcMain.handle("set-job-automation", (_event, updates: { search?: any; resumeRefresh?: any }) => {
  const config = store.get("config") || {};
  const automation = { ...(config.job_automation || {}) };
  if (updates.search) {
    automation.search = {
      ...automation.search,
      ...updates.search,
      intervalHours: clampIntervalHours("search", updates.search.intervalHours),
    };
  }
  if (updates.resumeRefresh) {
    automation.resumeRefresh = {
      ...automation.resumeRefresh,
      ...updates.resumeRefresh,
      intervalHours: clampIntervalHours("resumeRefresh", updates.resumeRefresh.intervalHours),
    };
  }
  store.set("config", { ...config, job_automation: automation });
  rescheduleJobAutomation();
  return automation;
});

app.on("ready", () => {
  initJobAutomation({
    getConfig: () => store.get("config") || {},
    setConfig: (config) => store.set("config", config),
    broadcast,
  });
});

// API keys were being written to config.json in plain text - found while
// debugging a real user's config on disk. safeStorage ties encryption to
// the OS user account (DPAPI on Windows, Keychain on macOS, libsecret on
// Linux), so unlike electron-store's own encryptionKey option, there's no
// key we have to generate or hide somewhere ourselves.
const ENCRYPTED_CONFIG_KEYS = [
  "deepgram_api_key",
  "sixtydb_api_key",
  "openai_key",
  "superjob_password",
  "superjob_client_secret",
  "superjob_api_app_id",
  "superjob_access_token",
  "superjob_refresh_token",
];
const ENC_PREFIX = "enc:";

function decryptSecret(value: string): string {
  if (!value.startsWith(ENC_PREFIX)) return value;
  try {
    return safeStorage.decryptString(Buffer.from(value.slice(ENC_PREFIX.length), "base64"));
  } catch {
    // Corrupt/foreign-machine ciphertext (e.g. config.json copied between
    // computers, where DPAPI can't decrypt it) - surface as empty rather
    // than leaking the ciphertext blob into a text field.
    return "";
  }
}

function encryptSecret(value: string): string {
  if (!value || value.startsWith(ENC_PREFIX)) return value;
  return ENC_PREFIX + safeStorage.encryptString(value).toString("base64");
}

function decryptConfig(config: Record<string, any>): Record<string, any> {
  const result = { ...config };
  for (const key of ENCRYPTED_CONFIG_KEYS) {
    const value = result[key];
    // No prefix - a pre-existing plaintext value from before this feature,
    // or encryption unavailable on this machine. Returned as-is either way.
    if (typeof value === "string") result[key] = decryptSecret(value);
  }
  if (Array.isArray(result.model_slots)) {
    result.model_slots = result.model_slots.map((slot: any) =>
      typeof slot?.apiKey === "string" ? { ...slot, apiKey: decryptSecret(slot.apiKey) } : slot
    );
  }
  return result;
}

function encryptConfig(config: Record<string, any>): Record<string, any> {
  if (!safeStorage.isEncryptionAvailable()) return config;
  const result = { ...config };
  for (const key of ENCRYPTED_CONFIG_KEYS) {
    const value = result[key];
    if (typeof value === "string") result[key] = encryptSecret(value);
  }
  if (Array.isArray(result.model_slots)) {
    result.model_slots = result.model_slots.map((slot: any) =>
      typeof slot?.apiKey === "string" ? { ...slot, apiKey: encryptSecret(slot.apiKey) } : slot
    );
  }
  return result;
}

ipcMain.handle("get-config", () => {
  return decryptConfig(store.get("config") || {});
});

ipcMain.handle("get-encryption-available", () => {
  return safeStorage.isEncryptionAvailable();
});

ipcMain.handle("set-config", (event, config) => {
  store.set("config", encryptConfig(config));
});

// Reads via Electron's own clipboard API (main process), not the web
// Clipboard API - the renderer's permission handler denies everything except
// "media", which would otherwise block clipboard-read entirely.
ipcMain.handle("read-clipboard-image", () => {
  const image = clipboard.readImage();
  if (image.isEmpty()) return null;
  return image.toDataURL();
});

ipcMain.handle("read-clipboard-text", () => clipboard.readText());

// Region-select screenshot: a full-screen, click-enabled, content-protected
// overlay the user drags a rectangle on, closed the instant the drag ends -
// so it never lingers in front of whatever's being screen-shared.
let selectionWindow: BrowserWindow | null = null;

function createSelectionWindow(): void {
  if (selectionWindow && !selectionWindow.isDestroyed()) return;
  const display = screen.getPrimaryDisplay();

  selectionWindow = new BrowserWindow({
    x: display.bounds.x,
    y: display.bounds.y,
    width: display.bounds.width,
    height: display.bounds.height,
    frame: false,
    transparent: true,
    // Windows renders a transparent BrowserWindow as solid black until an
    // explicit alpha backgroundColor is set - without it the window showed
    // before the renderer painted, covering the whole screen with black.
    backgroundColor: "#00000000",
    resizable: false,
    movable: false,
    fullscreenable: false,
    skipTaskbar: true,
    hasShadow: false,
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      webSecurity: false,
    },
  });

  selectionWindow.setAlwaysOnTop(true, "screen-saver");
  selectionWindow.setContentProtection(true);
  selectionWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  selectionWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY + "#/region-select");
  selectionWindow.once("ready-to-show", () => {
    selectionWindow?.show();
  });

  selectionWindow.on("closed", () => {
    selectionWindow = null;
  });
}

ipcMain.handle("open-region-select", () => {
  createSelectionWindow();
});

ipcMain.handle("cancel-region-select", () => {
  selectionWindow?.close();
});

ipcMain.handle(
  "capture-region",
  async (event, rect: { x: number; y: number; width: number; height: number }) => {
    selectionWindow?.close();
    try {
      const display = screen.getPrimaryDisplay();
      const scaleFactor = display.scaleFactor;
      const captureWidth = Math.round(display.size.width * scaleFactor);
      const captureHeight = Math.round(display.size.height * scaleFactor);

      const sources = await desktopCapturer.getSources({
        types: ["screen"],
        thumbnailSize: { width: captureWidth, height: captureHeight },
      });
      if (!sources[0] || sources[0].thumbnail.isEmpty()) {
        broadcast("region-captured", { dataUrl: null, error: "Could not capture the screen." });
        return;
      }

      const cropped = sources[0].thumbnail.crop({
        x: Math.max(0, Math.round(rect.x * scaleFactor)),
        y: Math.max(0, Math.round(rect.y * scaleFactor)),
        width: Math.max(1, Math.round(rect.width * scaleFactor)),
        height: Math.max(1, Math.round(rect.height * scaleFactor)),
      });
      broadcast("region-captured", { dataUrl: cropped.toDataURL() });
    } catch (err: any) {
      broadcast("region-captured", { dataUrl: null, error: err?.message || "Screenshot failed." });
    }
  }
);

ipcMain.handle("parsePDF", async (event, pdfBuffer) => {
  try {
    const pdf = require("pdf-parse");
    const data = await pdf(Buffer.from(pdfBuffer), {
      max: 0,
    });
    return { text: data.text };
  } catch (error) {
    return { error: "Failed to parse PDF: " + error.message };
  }
});

ipcMain.handle("process-image", async (event, imageData) => {
  try {
    const sharp = require("sharp");
    let image;
    if (imageData.startsWith("data:image")) {
      const base64Data = imageData.split(",")[1];
      const imageBuffer = Buffer.from(base64Data, "base64");
      image = sharp(imageBuffer);
    } else {
      throw new Error(
        "Invalid image input: expected Base64 encoded image data"
      );
    }
    const metadata = await image.metadata();
    return `Image size: ${metadata.width}x${metadata.height}, Format: ${metadata.format}`;
  } catch (error) {
    return { error: "Failed to process image: " + error.message };
  }
});

ipcMain.handle("highlightCode", async (event, code, language) => {
  return Prism.highlight(code, Prism.languages[language], language);
});

app.on("ready", () => {
  session.defaultSession.setDisplayMediaRequestHandler(
    (request, callback) => {
      desktopCapturer.getSources({ types: ["screen"] }).then((sources) => {
        callback({ video: sources[0], audio: "loopback" });
      });
    },
    { useSystemPicker: true }
  );

  ipcMain.handle(
    "transcribe-audio",
    async (event, audioBuffer: ArrayBuffer, config) => {
      try {
        const tempFilePath = path.join(
          app.getPath("temp"),
          `temp_audio_${Date.now()}.wav`
        );
        fs.writeFileSync(tempFilePath, Buffer.from(audioBuffer));

        const formData = new FormData();
        formData.append("file", fs.createReadStream(tempFilePath), {
          filename: "audio.wav",
          contentType: "audio/wav",
        });
        formData.append("model", "whisper-1");

        if (config.primaryLanguage && config.primaryLanguage !== "auto") {
          formData.append("language", config.primaryLanguage);
        }
        if (config.secondaryLanguage) {
          formData.append(
            "prompt",
            `This audio may contain ${config.primaryLanguage} and ${config.secondaryLanguage}.`
          );
        }

        const baseUrl = normalizeApiBaseUrl(config.api_base);
        const apiUrl = `${baseUrl}/audio/transcriptions`;
        const response = await axios.post(apiUrl, formData, {
          headers: {
            ...formData.getHeaders(),
            Authorization: `Bearer ${config.openai_key}`,
          },
          maxContentLength: Infinity,
          maxBodyLength: Infinity,
        });

        fs.unlinkSync(tempFilePath);

        return response.data;
      } catch (error) {
        throw error;
      }
    }
  );
});

const activeAskControllers = new Map<string, AbortController>();

ipcMain.handle(
  "ask-llm",
  async (
    event,
    {
      config,
      mode,
      messages,
    }: {
      config: any;
      mode: InterviewMode;
      messages: { role: string; content: string; attachments?: { dataUrl: string }[] }[];
    }
  ) => {
    const requestId = `${Date.now()}-${Math.random().toString(36).slice(2)}`;
    const abortController = new AbortController();
    activeAskControllers.set(requestId, abortController);

    try {
      let content = "";
      for await (const chunk of askWithMode(
        config,
        mode,
        messages as any,
        { signal: abortController.signal }
      )) {
        content += chunk.delta;
        broadcast("llm-chunk", { requestId, delta: chunk.delta });
      }
      broadcast("llm-done", { requestId });
      return { requestId, content };
    } catch (error: any) {
      if (error?.name === "AbortError") {
        broadcast("llm-done", { requestId, aborted: true });
      } else {
        broadcast("llm-error", { requestId, error: error?.message || "Unknown error occurred" });
      }
      return { requestId, error: error?.message || "Unknown error occurred" };
    } finally {
      activeAskControllers.delete(requestId);
    }
  }
);

// Used only by the question-detection classifier's ambiguous-fragment
// fallback - deliberately bypasses askWithMode (no mode system prompt
// prepended, since it needs its own YES/NO-only instruction to actually be
// followed) and never broadcasts llm-chunk/llm-done, so it can't leak into
// the visible chat's streaming-answer state.
ipcMain.handle("classify-fragment", async (_event, { config, text }: { config: any; text: string }) => {
  try {
    const provider = getProvider(config);
    let content = "";
    for await (const chunk of provider.ask(
      [
        {
          role: "system",
          content:
            "You will be shown a fragment of live speech transcription. Reply with exactly one word, " +
            "YES or NO - nothing else. YES means this fragment is a question or request directed at the " +
            "listener that needs an answer. NO means it's small talk, an incomplete thought, or noise.",
        },
        { role: "user", content: text },
      ],
      {}
    )) {
      content += chunk.delta;
    }
    return { content };
  } catch (error: any) {
    return { error: error?.message || "Unknown error occurred" };
  }
});

ipcMain.handle("cancel-llm", (event, requestId: string) => {
  const controller = activeAskControllers.get(requestId);
  if (controller) {
    controller.abort();
  }
});

ipcMain.handle("get-desktop-sources", async () => {
  try {
    const sources = await desktopCapturer.getSources({
      types: ["window", "screen"],
    });
    return sources.map((source) => ({
      id: source.id,
      name: source.name,
      thumbnail: source.thumbnail.toDataURL(),
    }));
  } catch (error) {
    return [];
  }
});

// Real-time speech-to-text, provider-agnostic.
// The renderer talks to a single set of channels (start-stt / send-audio /
// stop-stt) and listens for unified events (stt-transcript / stt-status /
// stt-error). Internally we route to either Deepgram (via @deepgram/sdk) or
// 60db (via a raw WebSocket). Both expect 16 kHz, mono, 16-bit linear PCM,
// which is exactly what InterviewPage produces.

// Active connections. Only one provider is active at a time.
let deepgramConnection: any = null;
let sixtydbSocket: WebSocket | null = null;
let activeProvider: "deepgram" | "60db" | null = null;

function startDeepgram(event: Electron.IpcMainInvokeEvent, config: any) {
  if (!config.deepgram_key) {
    throw new Error("Deepgram API key missing");
  }
  const deepgram = createClient(config.deepgram_key);

  // Settings defaults primaryLanguage to "auto", but Deepgram's live API does
  // NOT accept "auto" as a language code - it silently misbehaves. Real
  // auto-detection needs the separate detect_language flag instead. This was
  // the actual cause of STT "not working" for anyone who left the default.
  const wantsAutoDetect = !config.primaryLanguage || config.primaryLanguage === "auto";

  deepgramConnection = deepgram.listen.live({
    punctuate: true,
    // Interim (non-final) results are forwarded on their own "stt-interim"
    // channel purely for a live "Hearing: ..." caption - the committed
    // transcript buffer that drives auto-submit still only ever advances on
    // is_final, so this is a zero-risk display improvement, not a latency
    // shortcut for submission itself (see the dynamic silence window below
    // for that).
    interim_results: true,
    // nova-3 is Deepgram's current flagship model with the broadest
    // multi-language support (Russian included); nova-2 is the older,
    // English-first default. endpointing is how much trailing silence it
    // waits for before finalizing a transcript - 1500ms was adding 1.5s of
    // dead air after every question before the assistant even saw the text.
    model: "nova-3",
    ...(wantsAutoDetect ? { detect_language: true } : { language: config.primaryLanguage }),
    encoding: "linear16",
    sample_rate: 16000,
    endpointing: 300,
  });

  deepgramConnection.addListener(LiveTranscriptionEvents.Open, () => {
    broadcast("stt-status", { status: "open", provider: "deepgram" });
  });

  deepgramConnection.addListener(LiveTranscriptionEvents.Close, () => {
    broadcast("stt-status", { status: "closed", provider: "deepgram" });
  });

  deepgramConnection.addListener(
    LiveTranscriptionEvents.Transcript,
    (data: any) => {
      const transcript = data?.channel?.alternatives?.[0]?.transcript;
      if (!transcript) return;
      if (data.is_final) {
        broadcast("stt-transcript", { transcript, is_final: true });
      } else {
        broadcast("stt-interim", { transcript });
      }
    }
  );

  deepgramConnection.addListener(LiveTranscriptionEvents.Error, (err: any) => {
    broadcast("stt-error", { provider: "deepgram", error: err });
  });

  return new Promise<void>((resolve, reject) => {
    deepgramConnection.addListener(LiveTranscriptionEvents.Open, () =>
      resolve()
    );
    deepgramConnection.addListener(LiveTranscriptionEvents.Error, reject);
    setTimeout(() => reject(new Error("Deepgram timeout")), 10000);
  });
}

function start60dbStt(event: Electron.IpcMainInvokeEvent, config: any) {
  if (!config.sixtydb_key) {
    throw new Error("60db API key missing");
  }
  const url = `wss://api.60db.ai/ws/stt?apiKey=${encodeURIComponent(
    config.sixtydb_key
  )}`;
  const socket = new WebSocket(url);
  sixtydbSocket = socket;

  return new Promise<void>((resolve, reject) => {
    const timeout = setTimeout(
      () => reject(new Error("60db STT timeout")),
      10000
    );

    socket.on("open", () => {
      // Tell 60db we will stream browser PCM (linear) at 16 kHz.
      const language =
        config.primaryLanguage && config.primaryLanguage !== "auto"
          ? config.primaryLanguage
          : "en";
      socket.send(
        JSON.stringify({
          type: "start",
          languages: [language],
          config: {
            encoding: "linear",
            sample_rate: 16000,
            utterance_end_ms: 1000,
            continuous_mode: true,
            interim_results_frequency: 0,
            audio_enhancement: "adaptive",
            diarize: false,
          },
        })
      );
    });

    socket.on("message", (raw: WebSocket.RawData) => {
      let msg: any;
      try {
        msg = JSON.parse(raw.toString());
      } catch {
        return;
      }

      // Server is ready for audio.
      if (msg.type === "connected") {
        clearTimeout(timeout);
        broadcast("stt-status", { status: "open", provider: "60db" });
        resolve();
        return;
      }

      // Final transcript. We only forward the canonical (speech_final) result
      // with non-empty text, mirroring the Deepgram is_final filter.
      if (msg.type === "transcription" && msg.text && msg.text.trim()) {
        if (msg.speech_final === true) {
          broadcast("stt-transcript", { transcript: msg.text, is_final: true });
        } else {
          // interim_results_frequency is 0 above, so 60db likely never sends
          // this today - forwarded defensively in case that changes, same
          // display-only channel Deepgram's interim results use.
          broadcast("stt-interim", { transcript: msg.text });
        }
        return;
      }

      if (msg.type === "error") {
        broadcast("stt-error", { provider: "60db", error: msg });
      }
    });

    socket.on("error", (err) => {
      clearTimeout(timeout);
      broadcast("stt-error", { provider: "60db", error: err.message });
      reject(err);
    });

    socket.on("close", () => {
      broadcast("stt-status", { status: "closed", provider: "60db" });
    });
  });
}

ipcMain.handle("start-stt", async (event, config) => {
  try {
    const provider: "deepgram" | "60db" =
      config.stt_provider === "60db" ? "60db" : "deepgram";
    activeProvider = provider;

    if (provider === "60db") {
      await start60dbStt(event, config);
    } else {
      await startDeepgram(event, config);
    }
    return { success: true };
  } catch (error) {
    activeProvider = null;
    return { success: false, error: error.message };
  }
});

ipcMain.handle("send-audio", async (event, audioData) => {
  try {
    const buffer = Buffer.from(audioData);
    if (activeProvider === "deepgram" && deepgramConnection) {
      deepgramConnection.send(buffer);
    } else if (
      activeProvider === "60db" &&
      sixtydbSocket &&
      sixtydbSocket.readyState === WebSocket.OPEN
    ) {
      sixtydbSocket.send(
        JSON.stringify({
          type: "audio",
          audio: buffer.toString("base64"),
          encoding: "linear",
          sample_rate: 16000,
        })
      );
    }
  } catch (error) {
    console.error("failed to send audio to STT provider:", error);
  }
});

ipcMain.handle("stop-stt", () => {
  if (deepgramConnection) {
    try {
      deepgramConnection.finish();
    } catch {
      /* ignore */
    }
    deepgramConnection = null;
  }
  if (sixtydbSocket) {
    try {
      if (sixtydbSocket.readyState === WebSocket.OPEN) {
        sixtydbSocket.send(JSON.stringify({ type: "stop" }));
      }
      sixtydbSocket.close();
    } catch {
      /* ignore */
    }
    sixtydbSocket = null;
  }
  activeProvider = null;
});

ipcMain.handle("speak-60db", async (event, { text, config }) => {
  return invoke60dbSpeak(text, config);
});

ipcMain.handle("get-60db-voices", async (event, config) => {
  try {
    if (!config.sixtydb_api_key) {
      throw new Error("60db API key missing");
    }
    const response = await axios.get("https://api.60db.ai/myvoices", {
      headers: { Authorization: `Bearer ${config.sixtydb_api_key}` },
    });
    const data = response.data || {};
    return { success: true, voices: Array.isArray(data.data) ? data.data : [] };
  } catch (error: any) {
    const message = axios.isAxiosError(error)
      ? error.response
        ? `60db voices error: ${error.response.status} ${error.response.statusText}`
        : error.message
      : error.message || "Unknown error";
    return { success: false, error: message, voices: [] };
  }
});

// Dispatches to whichever TTS provider is configured. Web Speech isn't
// handled here - it runs entirely in the renderer via window.speechSynthesis,
// since there's no main-process equivalent of that browser API.
ipcMain.handle("speak-tts", async (event, { text, config }) => {
  if (config.tts_provider === "openai") return tts.synthesizeOpenAI(text, config);
  return invoke60dbSpeak(text, config);
});

async function invoke60dbSpeak(text: string, config: any) {
  try {
    if (!config.sixtydb_api_key) {
      throw new Error("60db API key missing");
    }
    if (!text || !text.trim()) {
      throw new Error("No text to synthesize");
    }
    const response = await axios.post(
      "https://api.60db.ai/tts-synthesize",
      { text: text.slice(0, 5000), voice_id: config.sixtydb_voice_id || undefined, output_format: "mp3", speed: 1 },
      {
        headers: { Authorization: `Bearer ${config.sixtydb_api_key}`, "Content-Type": "application/json" },
        maxContentLength: Infinity,
        maxBodyLength: Infinity,
      }
    );
    const data = response.data || {};
    if (!data.audio_base64) throw new Error(data.message || "60db returned no audio");
    return { success: true, audio_base64: data.audio_base64, output_format: data.output_format || "mp3" };
  } catch (error: any) {
    const message = axios.isAxiosError(error)
      ? error.response
        ? `60db TTS error: ${error.response.status} ${error.response.statusText}`
        : error.message
      : error.message || "Unknown error";
    return { success: false, error: message };
  }
}

ipcMain.handle("get-tts-voices", async (event, config) => {
  if (config.tts_provider === "openai") return { success: true, voices: tts.listOpenAIVoices() };
  return null;
});
